name: Validate JSON

on:
  pull_request:
    branches:
      - main

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate JSON
      uses: json-yaml-validate/json-yaml-validate@v1
      with:
        files: './data/*.json'